apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-efs-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e2dc5966adbfb99c


