apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e2dc5966adbfb99c

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-pv

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-test-pod
spec:
  containers:
    - name: efs-test-container
      image: amazonlinux
      command: ["/bin/sh"]
      args: ["-c", "echo 'EFS Test Successful!' > /mnt/efs/testfile && tail -f /dev/null"]
      volumeMounts:
        - name: efs-storage
          mountPath: /mnt/efs
  volumes:
    - name: efs-storage
      persistentVolumeClaim:
        claimName: efs-pvc
