apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    io.kompose.service: moodle
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
    - name: "443"
      port: 443
      targetPort: 8443
  selector:
    io.kompose.service: moodle
